# v1.x XRD (creates cluster-scoped XRs by default)
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabases.aws.platform.tekanaid.com
spec:
  group: aws.platform.tekanaid.com
  names:
    kind: XDatabase
    plural: xdatabases
  # NO scope field = cluster-scoped (v1.x default behavior)
  claimNames:
    kind: DatabaseClaim
    plural: databaseclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  storageGB:
                    type: integer
                    minimum: 20
                    maximum: 1000
                  tableType:
                    type: string
                    enum: ["transactional", "analytics"]
                  environment:
                    type: string
                    enum: ["development", "staging", "production"]
                required:
                - storageGB
                - tableType
                - environment
